import { writeFileSync } from "fs";
import { resolve } from "path";
import type { GatewayConfig } from "./types";
import { discoverTools, type DiscoveredTool } from "./utils";
import { classifyTool, type TrustLevel } from "./classify";

interface PolicyTool {
  qualifiedName: string;
  server: string;
  description: string;
  trust: TrustLevel;
  inputFields: string[];
}

export async function generatePolicy(
  config: GatewayConfig,
  outputPath: string
): Promise<void> {
  const tools: PolicyTool[] = [];

  for (const [name, cfg] of Object.entries(config.servers)) {
    try {
      const { tools: discovered, transport } = await discoverTools(name, cfg);
      for (const t of discovered) {
        tools.push({
          ...t,
          trust: classifyTool(t.qualifiedName),
        });
      }
      await transport.close();
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      console.error(`[!] Failed to connect to "${name}": ${message}`);
    }
  }

  if (tools.length === 0) {
    console.error("No tools discovered — cannot generate policy.");
    process.exit(1);
  }

  const rego = buildRego(tools);
  const dest = resolve(outputPath);
  writeFileSync(dest, rego, "utf-8");

  const low = tools.filter((t) => t.trust === "low").length;
  const med = tools.filter((t) => t.trust === "medium").length;
  const high = tools.filter((t) => t.trust === "high").length;

  console.log(`Generated trust-classified policy with ${tools.length} tool(s) → ${dest}`);
  console.log(`  LOW: ${low}  MEDIUM: ${med}  HIGH: ${high}`);
  console.log(`\nEdit the file to customize which tools to allow or block.`);
  console.log(`Then start the agent:\n`);
  console.log(`  authzx-agent --policy ${outputPath}\n`);

  process.exit(0);
}

function buildRego(tools: PolicyTool[]): string {
  const servers = [...new Set(tools.map((t) => t.server))];
  const lines: string[] = [];
  const now = new Date().toISOString();
  const total = tools.length;

  lines.push("# Auto-generated by AuthzX MCP Gateway");
  lines.push(`# ${servers.length} server(s), ${total} tool(s) discovered`);
  lines.push(`# Generated: ${now}`);
  lines.push("#");
  lines.push("# Trust levels:");
  lines.push("#   LOW    — read-only operations, allowed by default");
  lines.push("#   MEDIUM — write/execute operations, requires explicit subject approval");
  lines.push("#   HIGH   — destructive operations, blocked by default");
  lines.push("#");
  lines.push("# Edit this file to customize your policy.");
  lines.push("# Run: authzx-agent --policy ./policy.rego");
  lines.push("");
  lines.push("package authzx.mcp");
  lines.push("");
  lines.push("default allow := false");

  const low = tools.filter((t) => t.trust === "low").sort(byName);
  const medium = tools.filter((t) => t.trust === "medium").sort(byName);
  const high = tools.filter((t) => t.trust === "high").sort(byName);

  if (low.length > 0) {
    lines.push("");
    lines.push("# ── LOW trust (allowed for all approved agents) ──────────────");
    lines.push("");
    for (const t of low) {
      const warning = toolWarning(t);
      if (warning) lines.push(`# ${warning}`);
      lines.push(`allow if {`);
      lines.push(`    input.resource.name == "${t.qualifiedName}"`);
      lines.push(`}`);
      lines.push("");
    }
  }

  if (medium.length > 0) {
    lines.push("# ── MEDIUM trust (allowed for specific agents) ───────────────");
    lines.push("# Replace subject values with your actual agent identities");
    lines.push("");
    for (const t of medium) {
      const warning = toolWarning(t);
      if (warning) lines.push(`# ${warning}`);
      lines.push(`allow if {`);
      lines.push(`    input.resource.name == "${t.qualifiedName}"`);
      lines.push(`    input.subject.id in {"agent:cursor", "agent:claude"}`);
      lines.push(`}`);
      lines.push("");
    }
  }

  if (high.length > 0) {
    lines.push("# ── HIGH trust (blocked by default — uncomment to allow) ─────");
    lines.push("# DANGER: these are destructive operations.");
    lines.push("# Uncomment and specify exact subjects before enabling.");
    lines.push("");
    for (const t of high) {
      lines.push(`# allow if {`);
      lines.push(`#     input.resource.name == "${t.qualifiedName}"`);
      lines.push(`#     input.subject.id == "agent:claude"  # be explicit`);
      lines.push(`# }`);
      lines.push("");
    }
  }

  return lines.join("\n");
}

function byName(a: PolicyTool, b: PolicyTool): number {
  return a.qualifiedName.localeCompare(b.qualifiedName);
}

function toolWarning(t: PolicyTool): string | null {
  const name = t.qualifiedName.toLowerCase();
  if (/execute/.test(name)) {
    return `WARNING: ${t.qualifiedName} can run destructive operations — review carefully`;
  }
  if (/query/.test(name)) {
    return `WARNING: ${t.qualifiedName} — raw queries can be destructive, consider moving to MEDIUM`;
  }
  return null;
}
